# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [/assets/css/bootstrap/bootstrap.min.css,/assets/css/main-robolivre.css]

  javascripts:    [/assets/bootstrap/js/bootstrap.min.js,/assets/js/jquery.placeholder.min.js,/assets/js/jquery.imagesloaded.min.js,/assets/js/jquery.masonry.min.js,/assets/js/jquery.autoresize.min.js,/assets/js/CLEditor1_3_0/jquery.cleditor.min.js, /assets/js/autoSuggestv14/jquery.autoSuggest.minified.js,  /assets/js/file-uploader/fileuploader.js  ,/assets/js/main-robolivre.js]

  has_layout:     true
  layout:         layout
